### ISSUE TITLE
Excuse me, are you considering sorting out spconv2.1?

### ISSUE THREAD

**Issue by Kong-LYY** [neeharperi/spconv#1]

**Comment by neeharperi** [comment]
No plans at the moment. This repository is just to support the installation of FutureDet. I'm planning on integrating FutureDet with mmdetection3d, which already supports spconv2.x

**Comment by Kong-LYY** [comment]
I tested in the algorithm, spcon2. X is at least 2 times faster than 1.2. But the code itself is not flexible enough, and I see that you change spconv1.2 very standardly, so I want to see how you will change spconv2.X.
